services:
  identidock:
    build: .
    ports:
      - "55000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.1

  redis:
    image: redis:3.19
