services:
  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.1

  redis:
    image: redis:alpine3.19

